In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.tree import plot_tree
from timeit import default_timer as timer
import time
import statistics
from sklearn import tree

In [2]:
path = r"/Users/nasim/Desktop/data/Flu_Classification.csv"
df = pd.read_csv(path)
df.head()

,Age,Temperature,Sex,Diarrhea,Fever,Coughing,ShortnessOfBreath,SoreThroat,NauseaVomitting,Fatigue,Cancer,Diagnosis
0,67.0,38.11,F,unknown,Yes,Yes,unknown,No,unknown,No,unknown,H1N1
1,29.0,0.00,M,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,H1N1
2,22.0,0.00,F,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,H1N1
3,20.0,36.56,F,unknown,Yes,Yes,unknown,No,unknown,Yes,unknown,H1N1
4,21.0,0.00,M,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,H1N1

In [3]:
df = df.astype(str)

In [4]:
df.Diagnosis = df.Diagnosis.astype("category").cat.codes
df.Sex = df.Sex.astype("category").cat.codes
df.Diarrhea = df.Diarrhea.astype("category").cat.codes
df.Fever = df.Fever.astype("category").cat.codes
df.Coughing = df.Coughing.astype("category").cat.codes
df.ShortnessOfBreath = df.ShortnessOfBreath.astype("category").cat.codes
df.SoreThroat = df.SoreThroat.astype("category").cat.codes
df.NauseaVomitting = df.NauseaVomitting.astype("category").cat.codes
df.Fatigue = df.Fatigue.astype("category").cat.codes
df.Cancer = df.Cancer.astype("category").cat.codes

In [5]:
# iterating over rows using iterrows() function 
for index, row in df.iterrows():
    if row['SoreThroat'] == 'M':
        print(True)

In [6]:
df.dtypes

Age                  object
Temperature          object
Sex                    int8
Diarrhea               int8
Fever                  int8
Coughing               int8
ShortnessOfBreath      int8
SoreThroat             int8
NauseaVomitting        int8
Fatigue                int8
Cancer                 int8
Diagnosis              int8
dtype: object

In [7]:
x = df[["Age", "Temperature", "Sex", "Diarrhea", "Fever", "Coughing", "ShortnessOfBreath", "SoreThroat", "NauseaVomitting", "Fatigue", "Cancer"]]
y = df['Diagnosis']

In [8]:
x

,Age,Temperature,Sex,Diarrhea,Fever,Coughing,ShortnessOfBreath,SoreThroat,NauseaVomitting,Fatigue,Cancer
0,67.0,38.11,0,2,1,1,2,0,2,0,1
1,29.0,0.0,1,2,2,2,2,2,2,2,1
2,22.0,0.0,0,2,2,2,2,2,2,2,1
3,20.0,36.56,0,2,1,1,2,0,2,1,1
4,21.0,0.0,1,2,2,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...
1480,1.4,0.0,2,2,2,2,2,2,2,2,1
1481,0.83,0.0,2,2,2,2,2,2,2,2,1
1482,3.0,0.0,2,2,2,2,2,2,2,2,1
1483,4.0,0.0,2,2,2,2,2,2,2,2,1
1484,6.0,0.0,2,2,2,2,2,2,2,2,1

In [9]:
def gini_tree():
    a = timer()
    

    dt1 = DecisionTreeClassifier(criterion = "gini")
    scores = cross_val_score(dt1, x, y, cv= 40)
    b = timer()

    delta = b - a
    #print("Accuracy: " + str(scores.mean()))
    #print("Time taken to generate tree: " + str(delta) + " second")
    return scores.mean(), delta

In [10]:
# Python program to get average of a list
def average_list(lst):
    return mean(lst)

In [11]:
accuracies = []
times = []
for _ in range(30):
    acc, gtime = gini_tree()
    accuracies.append(acc)
    times.append(gtime)

converted_accuracies = [float(x) for x in accuracies]
converted_times =  [float(x) for x in times]

avg_accuracy = statistics.mean(converted_accuracies)
avg_time = statistics.mean(converted_times)

print('Accuracy: {}'.format(avg_accuracy))
print('Average generation time : {} sec'.format(avg_time))

Accuracy: 0.8903028686581319
Average generation time : 0.3819606921333332 sec

In [12]:
# Cross Validation 10 folds : Info Gain

def create_dt_infogain():
    a = timer()
    dt1 = DecisionTreeClassifier(criterion = "entropy")
    scores = cross_val_score(dt1, x, y, cv=40)
    b = timer()

    delta = b - a
    #print("Accuracy: " + str(scores.mean()))
    #print("Time taken to generate tree: " + str(delta) + " second")
    accuracy = str(scores.mean())
    generation_time = str(delta)
    return accuracy,generation_time

In [13]:
accuracies = []
times = []
for _ in range(30):
    acc, gtime = create_dt_infogain()
    accuracies.append(acc)
    times.append(gtime)

conveted_accuracies = [float(x) for x in accuracies]
converted_times =  [float(x) for x in times]

avg_accuracy = statistics.mean(conveted_accuracies)
avg_time = statistics.mean(converted_times)

print('Accuracy: {}'.format(avg_accuracy))
print('Average generation time : {} sec'.format(avg_time))

Accuracy: 0.8933054765291607
Average generation time : 0.3175174585000004 sec