In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from sklearn.tree import plot_tree
from sklearn.model_selection import cross_val_score
from timeit import default_timer as timer
import time

c:\users\49171\appdata\local\programs\python\python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\49171\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\users\49171\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
path = r"C:\Users\49171\Desktop\Graph-Database-Learning-Algorithms-Neo4j\Dataset 2 - Metaprotein\Metaprotein_50.csv"
df = pd.read_csv(path)
df.head()

,25,36,81,128,171,237,1251,1254,2499,13,...,370,698,702,827,838,1227,1645,21,23,Patient.Type
0,151,6,28,21,15,15,8,6,30,38,...,2,379,167,26,50,6,42,82,0,C
1,41,10,52,37,21,16,11,4,99,23,...,5,306,136,8,7,3,26,30,4,C
2,23,19,37,13,7,8,5,1,108,1001,...,0,128,64,2,10,2,0,33,0,C
3,286,8,87,21,14,12,2,2,79,749,...,6,281,136,4,27,1,24,35,0,C
4,34,29,59,65,39,6,3,2,37,215,...,13,159,0,12,23,0,18,57,0,C

In [10]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

,25,36,81,128,171,237,1251,1254,2499,13,...,294,370,698,702,827,838,1227,1645,21,23
0,151,6,28,21,15,15,8,6,30,38,...,31,2,379,167,26,50,6,42,82,0
1,41,10,52,37,21,16,11,4,99,23,...,0,5,306,136,8,7,3,26,30,4
2,23,19,37,13,7,8,5,1,108,1001,...,2,0,128,64,2,10,2,0,33,0
3,286,8,87,21,14,12,2,2,79,749,...,0,6,281,136,4,27,1,24,35,0
4,34,29,59,65,39,6,3,2,37,215,...,3,13,159,0,12,23,0,18,57,0

In [6]:
# Cross Validation 10 folds : Gini
a = timer()
dt1 = DecisionTreeClassifier(criterion = "gini")
scores = cross_val_score(dt1, x, y, cv=10)
b = timer()

delta = b - a
print("Accuracy: " + str(scores.mean()) + " second")
print("Time taken to generate tree: " + str(delta) + " second")

Accuracy: 0.68 second
Time taken to generate tree: 0.14594029999997815 second

In [7]:
# Cross Validation 10 folds : Info Gain
a = timer()
dt1 = DecisionTreeClassifier(criterion = "entropy")
scores = cross_val_score(dt1, x, y, cv=10)
b = timer()

delta = b - a
print("Accuracy: " + str(scores.mean()) + " %")
print("Time taken to generate tree: " + str(delta) + " second")

Accuracy: 0.68 second
Time taken to generate tree: 0.15264919999998483 second